DROP SCHEMA IF EXISTS `4ww3` ;
CREATE SCHEMA IF NOT EXISTS `4ww3` DEFAULT CHARACTER SET latin1 ;
USE `4ww3` ;

-- Table `4ww3`.`restaurants`
DROP TABLE IF EXISTS `4ww3`.`restaurants` ;
CREATE TABLE IF NOT EXISTS `4ww3`.`restaurants` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(1023) NULL DEFAULT NULL,
  `phone` VARCHAR(31) NULL DEFAULT NULL,
  `lat` DOUBLE NULL DEFAULT NULL,
  `long` DOUBLE NULL DEFAULT NULL,
  `pic_path` VARCHAR(2047) NULL DEFAULT NULL,
  `description` VARCHAR(8191) NULL DEFAULT NULL,
  `rating` VARCHAR(45) NULL DEFAULT NULL,
  `restaurantscol` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- Table `4ww3`.`reviews`
DROP TABLE IF EXISTS `4ww3`.`reviews` ;
CREATE TABLE IF NOT EXISTS `4ww3`.`reviews` (
  `review_id` INT(11) NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT(11) NOT NULL,
  `rating` SMALLINT(6) NOT NULL,
  `review` VARCHAR(2000) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `date_submitted` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- Table `4ww3`.`users`
DROP TABLE IF EXISTS `4ww3`.`users` ;
CREATE TABLE IF NOT EXISTS `4ww3`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(63) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(2047) NULL DEFAULT NULL,
  `pic_path` VARCHAR(4095) NULL DEFAULT NULL,
  `marketing` ENUM('YES', 'NO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;
